const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Anchor,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.destroy,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Plugins.Text,
		C3.Behaviors.Bullet,
		C3.Behaviors.Fade,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Behaviors.Platform.Acts.SetAcceleration,
		C3.Behaviors.Platform.Acts.SetDeceleration,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.Spawn
	];
};
self.C3_JsPropNameTable = [
	{Anchor: 0},
	{backgroundPhase01: 0},
	{lives: 0},
	{hasRunningBoost: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{DestroyOutside: 0},
	{ripHunter: 0},
	{Keyboard: 0},
	{Solid: 0},
	{tile01: 0},
	{tile02: 0},
	{barrier: 0},
	{backgroundPhase02: 0},
	{fragment: 0},
	{fragmentCount: 0},
	{fragmentBarExternal: 0},
	{fragmentBarInternal: 0},
	{spawnPoint: 0},
	{pressRToRestart: 0},
	{gameOverTitle: 0},
	{gameOverBackground: 0},
	{tileGoingHorizontal01: 0},
	{Bullet: 0},
	{tileGoingTop01: 0},
	{Fade: 0},
	{speedPowerUp01: 0},
	{ripHunterGhost: 0},
	{tile03: 0},
	{tile04: 0},
	{tile05: 0},
	{fragments: 0},
	{fragmentsMax: 0}
];

self.InstanceType = {
	backgroundPhase01: class extends self.ISpriteInstance {},
	ripHunter: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	tile01: class extends self.ISpriteInstance {},
	tile02: class extends self.ISpriteInstance {},
	barrier: class extends self.ISpriteInstance {},
	backgroundPhase02: class extends self.ISpriteInstance {},
	fragment: class extends self.ISpriteInstance {},
	fragmentCount: class extends self.ITextInstance {},
	fragmentBarExternal: class extends self.ISpriteInstance {},
	fragmentBarInternal: class extends self.ISpriteInstance {},
	spawnPoint: class extends self.ISpriteInstance {},
	pressRToRestart: class extends self.ITextInstance {},
	gameOverTitle: class extends self.ITextInstance {},
	gameOverBackground: class extends self.ISpriteInstance {},
	tileGoingHorizontal01: class extends self.ISpriteInstance {},
	tileGoingTop01: class extends self.ISpriteInstance {},
	speedPowerUp01: class extends self.ISpriteInstance {},
	ripHunterGhost: class extends self.ISpriteInstance {},
	tile03: class extends self.ISpriteInstance {},
	tile04: class extends self.ISpriteInstance {},
	tile05: class extends self.ISpriteInstance {}
}